package com.desiseducare.models;

import javax.persistence.*;
import java.util.Date;

/**
 * a class that represents a User object stored in db
 */
@Entity
@Table

public class User {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    Integer userID;

    String password;

    @Column(unique = true)
    Integer dematAccountNumber;

    @Column(unique = true)
    String panCardNumber;
    @Column(unique = true)
    Integer aadharCardNumber;

    Boolean verificationStatus;

    @Column(unique = true)
    String email;
    Date dateAccountCreated;
    Date lastLogin;
    Float wallet;
    String userType; //RII,NII,Angel,otherQBI


    /**
     *
     * @return user type
     */
    public String getUserType() {
        return userType;
    }

    /**
     * Sets usertype
     * @param userType - Type of user - RII, NII, Angel, otherQBI
     */
    public void setUserType(String userType) {
        this.userType = userType;
    }

    /**
     * Empty constructor
     */
    public User() {
    }

    /**
     * Parameterised constructor
     * @param userID autogenerated with incrememt of 1, primary key in database
     * @param password 
     * @param email
     * @param userType  type of user - RII, NII, Angel, otherQBI
     * @param wallet default value 0.0
     */
    public User(Integer userID, String password, String email, String userType, Float wallet) {
        this.userID = userID;
        this.password = password;
        this.email = email;
        this.userType = userType;
        this.wallet = wallet;
    }

    public Integer getUserID() {
        return userID;
    }

    public void setUserID(Integer userID) {
        this.userID = userID;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public Integer getDematAccountNumber() {
        return dematAccountNumber;
    }

    public void setDematAccountNumber(Integer dematAccountNumber) {
        this.dematAccountNumber = dematAccountNumber;
    }

    public String getPanCardNumber() {
        return panCardNumber;
    }

    public void setPanCardNumber(String panCardNumber) {
        this.panCardNumber = panCardNumber;
    }

    public Integer getAadharCardNumber() {
        return aadharCardNumber;
    }

    public void setAadharCardNumber(Integer aadharCardNumber) {
        this.aadharCardNumber = aadharCardNumber;
    }

    public Boolean getVerificationStatus() {
        return verificationStatus;
    }

    public void setVerificationStatus(Boolean verificationStatus) {
        this.verificationStatus = verificationStatus;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Date getDateAccountCreated() {
        return dateAccountCreated;
    }

    public void setDateAccountCreated(Date dateAccountCreated) {
        this.dateAccountCreated = dateAccountCreated;
    }

    public Date getLastLogin() {
        return lastLogin;
    }

    public void setLastLogin(Date lastLogin) {
        this.lastLogin = lastLogin;
    }

    public Float getWallet() {
        return wallet;
    }

    public void setWallet(Float wallet) {
        this.wallet = wallet;
    }

    @Override
    public String toString() {
        return "User{" +
                "userID=" + userID +
                ", password='" + password + '\'' +
                ", dematAccountNumber=" + dematAccountNumber +
                ", panCardNumber='" + panCardNumber + '\'' +
                ", aadharCardNumber=" + aadharCardNumber +
                ", verificationStatus=" + verificationStatus +
                ", email='" + email + '\'' +
                ", dateAccountCreated=" + dateAccountCreated +
                ", lastLogin=" + lastLogin +
                ", wallet=" + wallet +
                ", userType='" + userType + '\'' +
                '}';
    }
}